
parameters:
  name: ''
  pool: ''
  sign: false

steps:
- task: UsePythonVersion@0
  displayName: Install python
  inputs:
    versionSpec: '$(python.version)'

- task: Cache@2
  displayName: Cache pip packages
  inputs:
    key: python | "$(Agent.OS)" | tox.ini | tests/requirements.txt | tests/ansible/requirements.txt
    restoreKeys: |
      python | "$(Agent.OS)" | tox.ini | tests/requirements.txt
      python | "$(Agent.OS)" | tox.ini
      python | "$(Agent.OS)"
      python
    path: $(PIP_CACHE_DIR)

- script: python -mpip --no-python-version-warning --disable-pip-version-check install tox==3.24.4
  displayName: Install tooling

- script: tox -e "$(tox.env)"
  displayName: "Run tests"
  env:
    AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
    AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
    AWS_DEFAULT_REGION: $(AWS_DEFAULT_REGION)
