#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2026 Mitogen authors <https://github.com/mitogen-hq>
# SPDX-License-Identifier: BSD-3-Clause
set -o errexit -o nounset -o pipefail

TESTS_SSH_PRIVATE_KEY_FILE='tests/data/docker/mitogen__has_sudo_pubkey.key'

chmod u=r,go= "$TESTS_SSH_PRIVATE_KEY_FILE"
