#!/usr/bin/env python
# SPDX-FileCopyrightText: 2026 Mitogen authors <https://github.com/mitogen-hq>
# SPDX-License-Identifier: BSD-3-Clause

import os
import subprocess

cmd = ';'.join([
    'from __future__ import print_function',
    'import os, sys',
    'print(sys.executable, os.path.realpath(sys.executable))',
])
for interpreter in ['/usr/bin/python', '/usr/bin/python2', '/usr/bin/python2.7']:
    print(interpreter)
    try:
        subprocess.call([interpreter, '-c', cmd])
    except OSError as exc:
        print(exc)

    print(interpreter, 'with PYTHON_LAUNCHED_FROM_WRAPPER=1')
    environ = os.environ.copy()
    environ['PYTHON_LAUNCHED_FROM_WRAPPER'] = '1'
    try:
        subprocess.call([interpreter, '-c', cmd], env=environ)
    except OSError as exc:
        print(exc)
